"""rename foreign key in posts (typo)

Revision ID: 07fb3d7bc3e5
Revises: 20db66a70f34
Create Date: 2018-07-24 14:06:31.071347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fb3d7bc3e5'
down_revision = '20db66a70f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('FK__posts__post_id__00200768', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('FK__posts__post_id__00200768', 'posts', 'users', ['post_id'], ['id'])
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
