"""fix user/posts relationship

Revision ID: 20db66a70f34
Revises: 9f5bffe44d5e
Create Date: 2018-07-24 14:05:33.794564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20db66a70f34'
down_revision = '9f5bffe44d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['post_id'], ['id'])
    op.drop_constraint('FK__users__post_id__76969D2E', 'users', type_='foreignkey')
    op.drop_column('users', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('FK__users__post_id__76969D2E', 'users', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'post_id')
    # ### end Alembic commands ###
