"""more fields in users table

Revision ID: be7687cfd12d
Revises: 68108f562860
Create Date: 2018-07-24 13:23:15.764926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7687cfd12d'
down_revision = '68108f562860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Enum('Male', 'Female', 'FTM', 'MTF', 'Fluid', name='gender'), nullable=True))
    op.add_column('user', sa.Column('gender_of_interests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender_of_interests')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
